// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADKM-I7EGQFYkYPJT_jgRvq8UkggvpI-4',
    appId: '1:409813632754:web:17d83907d1240b6d61326b',
    messagingSenderId: '409813632754',
    projectId: 'geosense-e1038',
    authDomain: 'geosense-e1038.firebaseapp.com',
    storageBucket: 'geosense-e1038.appspot.com',
    measurementId: 'G-324P20JZG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMojeny1d1gWlPqt3AkrjcRKLV8QWmfrQ',
    appId: '1:409813632754:android:2e3817265dd7894161326b',
    messagingSenderId: '409813632754',
    projectId: 'geosense-e1038',
    storageBucket: 'geosense-e1038.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Ab31zycSfnkoqf3-E6uuXyQUtrAlesQ',
    appId: '1:409813632754:ios:efe949f8ae0f5cab61326b',
    messagingSenderId: '409813632754',
    projectId: 'geosense-e1038',
    storageBucket: 'geosense-e1038.appspot.com',
    androidClientId: '409813632754-svqpj0h54cacgdermc1vdrhkovnlrr6k.apps.googleusercontent.com',
    iosClientId: '409813632754-eb18le7ddl1a9822a736h09756isod90.apps.googleusercontent.com',
    iosBundleId: 'com.example.riveAnimation',
  );
}
